language: node_js

node_js:
    - 13

cache:
    directories:
        - node_modules
        - .next

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: out
    on:
        branch: master

jobs:
    include:
        - stage: release
          node_js: lts/*
          script:
            - yarn lint
            - yarn build
            - yarn export
            - yarn semantic-release

notifications:
    email: false
