export default {
    wrapTokensWithVar: true,
    tokens: {
        colors: ["--colour-*", "--surface-*"],
        borderColors: ["--colour-*", "--surface-*"],
        spacing: ["--space-*"],
        borderRadius: ["--radius-*"],
        borderWidths: ["--border-width-*"],
        shadows: ["--shadow-*"],
        durations: ["--motion-dur-*"],
        fonts: ["--font-family-*", "--typography-font-family-*"],
        fontSizes: ["--typography-size-*"],
        fontWeights: ["--font-weight-*", "--typography-font-weight-*"],
        letterSpacings: [
            "--typography-letter-spacing-*",
            "--typography-tracking-*",
        ],
        lineHeights: ["--typography-line-*", "--typography-line-height-*"],
        opacity: ["--opacity-*"],
        zIndex: ["--z-*"],
        outlines: ["--border-focus-ring"],
    },
    rules: {
        "design-token/colors": "error",
        "design-token/border-color": "error",
        "design-token/spacing": "error",
        "design-token/border-radius": "error",
        "design-token/border-width": "error",
        "design-token/box-shadow": "error",
        "design-token/duration": "error",
        "design-token/font-family": "error",
        "design-token/font-size": "error",
        "design-token/font-weight": "error",
        "design-token/letter-spacing": "error",
        "design-token/line-height": "error",
        "design-token/opacity": "error",
        "design-token/z-index": "error",
        "design-token/outline": "error",
    },
};
