import { defineConfig } from "@lapidist/design-lint";

export default defineConfig({
    wrapTokensWithVar: true,
    tokens: {
        colors: ["--colour-*", "--surface-*"],
        spacing: ["--space-*"],
        borderRadius: ["--radius-*"],
        borderWidths: ["--border-width-*"],
        shadows: ["--shadow-*"],
        durations: ["--motion-dur-*"],
        lineHeights: ["--typography-line-*", "--typography-line-height-*"],
        fontWeights: ["--font-weight-*", "--typography-font-weight-*"],
        letterSpacings: [
            "--typography-tracking-*",
            "--typography-letter-spacing-*",
        ],
        zIndex: ["--z-*"],
        fontSizes: ["--typography-size-*"],
        fonts: ["--font-family-*", "--typography-font-family-*"],
        opacity: ["--opacity-*"],
        outlines: ["--border-focus-ring"],
        borderColors: ["--colour-*", "--surface-*"],
    },
    rules: {
        "design-token/colors": "error",
        "design-token/spacing": "error",
        "design-token/border-radius": "error",
        "design-token/border-width": "error",
        "design-token/box-shadow": "error",
        "design-token/duration": "error",
        "design-token/line-height": "error",
        "design-token/font-weight": "error",
        "design-token/letter-spacing": "error",
        "design-token/z-index": "error",
        "design-token/font-size": "error",
        "design-token/font-family": "error",
        "design-token/opacity": "error",
        "design-token/outline": "error",
        "design-token/border-color": "error",
    },
    ignoreFiles: ["styles/tokens.css"],
    patterns: ["components/**/*.{css,scss}", "styles/**/*.{css,scss}"],
});
