import styles from "./CaseStudies.module.scss";

export default function B2CVisual() {
    return (
        <svg className={styles.visual} aria-hidden="true" viewBox="0 0 256 144">
            <rect className="bg" width="256" height="144" />
            <rect
                className={styles.panel}
                x="-1"
                y="-1"
                width="258"
                height="18"
            />
            <rect
                className={styles.block}
                x="8"
                y="5"
                width="40"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="200"
                y="5"
                width="24"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="228"
                y="5"
                width="20"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="14"
                y="30"
                width="48"
                height="30"
                rx="2"
            />
            <rect
                className={styles.block}
                x="68"
                y="30"
                width="110"
                height="10"
                rx="1"
            />
            <rect
                className={styles.block}
                x="68"
                y="44"
                width="90"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="68"
                y="56"
                width="40"
                height="8"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="8"
                y="72"
                width="116"
                height="32"
                rx="2"
            />
            <rect
                className={styles.block}
                x="16"
                y="78"
                width="24"
                height="20"
                rx="2"
            />
            <rect
                className={styles.block}
                x="44"
                y="78"
                width="70"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="44"
                y="90"
                width="60"
                height="6"
                rx="1"
            />
            <rect
                className={styles.panel}
                x="132"
                y="72"
                width="116"
                height="32"
                rx="2"
            />
            <rect
                className={styles.block}
                x="140"
                y="78"
                width="24"
                height="20"
                rx="2"
            />
            <rect
                className={styles.block}
                x="168"
                y="78"
                width="70"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="168"
                y="90"
                width="60"
                height="6"
                rx="1"
            />
            <rect
                className={styles.panel}
                x="8"
                y="108"
                width="240"
                height="28"
                rx="2"
            />
            <rect
                className={styles.block}
                x="16"
                y="114"
                width="64"
                height="16"
                rx="2"
            />
            <rect
                className={styles.block}
                x="96"
                y="114"
                width="64"
                height="16"
                rx="2"
            />
            <rect
                className={styles.block}
                x="176"
                y="114"
                width="64"
                height="16"
                rx="2"
            />
        </svg>
    );
}
