import { BookCallButton } from "@/components/Cta/Cta";
import Card from "@/components/Card/Card";
import Section from "@/components/Section/Section";
import styles from "./CaseStudies.module.scss";

export default function CaseStudies() {
    return (
        <Section
            id="case-studies"
            heading="Case studies"
            className={styles.caseStudies}
        >
            <p className={styles.tagline}>Quality that holds as you scale.</p>

            <div className={styles.cards}>
                <Card title="Global fintech" size="md">
                    <svg
                        className={styles.visual}
                        aria-hidden="true"
                        viewBox="0 0 256 144"
                    >
                        <rect className="bg" width="256" height="144" />
                        <rect
                            className={styles.panel}
                            x="0"
                            y="0"
                            width="36"
                            height="144"
                        />
                        <rect
                            className={styles.block}
                            x="6"
                            y="8"
                            width="24"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="6"
                            y="24"
                            width="24"
                            height="6"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="6"
                            y="34"
                            width="24"
                            height="6"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="6"
                            y="44"
                            width="24"
                            height="6"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="6"
                            y="54"
                            width="24"
                            height="6"
                            rx="1"
                        />
                        <rect
                            className={styles.panel}
                            x="36"
                            y="0"
                            width="220"
                            height="20"
                        />
                        <rect
                            className={styles.block}
                            x="42"
                            y="6"
                            width="30"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="76"
                            y="6"
                            width="30"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="110"
                            y="6"
                            width="30"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.panel}
                            x="42"
                            y="28"
                            width="46"
                            height="20"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="94"
                            y="28"
                            width="46"
                            height="20"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="146"
                            y="28"
                            width="46"
                            height="20"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="198"
                            y="28"
                            width="46"
                            height="20"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="42"
                            y="54"
                            width="120"
                            height="50"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="168"
                            y="54"
                            width="76"
                            height="50"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="42"
                            y="110"
                            width="202"
                            height="26"
                            rx="2"
                        />
                    </svg>
                    <h4>Before:</h4>
                    <p>
                        Fragmented widgets, duplicated effort, inaccessible
                        flows.
                    </p>
                    <h4>After:</h4>
                    <p>
                        Unified tokens, audited patterns. CI checks keep
                        regressions out.
                    </p>
                </Card>
                <Card title="B2C SaaS" size="md">
                    <svg
                        className={styles.visual}
                        aria-hidden="true"
                        viewBox="0 0 256 144"
                    >
                        <rect className="bg" width="256" height="144" />
                        <rect
                            className={styles.panel}
                            x="0"
                            y="0"
                            width="256"
                            height="18"
                        />
                        <rect
                            className={styles.block}
                            x="8"
                            y="5"
                            width="40"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="200"
                            y="5"
                            width="24"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="228"
                            y="5"
                            width="20"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="14"
                            y="30"
                            width="48"
                            height="30"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="68"
                            y="30"
                            width="110"
                            height="10"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="68"
                            y="44"
                            width="90"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="68"
                            y="56"
                            width="40"
                            height="8"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="8"
                            y="72"
                            width="116"
                            height="32"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="16"
                            y="78"
                            width="24"
                            height="20"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="44"
                            y="78"
                            width="70"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="44"
                            y="90"
                            width="60"
                            height="6"
                            rx="1"
                        />
                        <rect
                            className={styles.panel}
                            x="132"
                            y="72"
                            width="116"
                            height="32"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="140"
                            y="78"
                            width="24"
                            height="20"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="168"
                            y="78"
                            width="70"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="168"
                            y="90"
                            width="60"
                            height="6"
                            rx="1"
                        />
                        <rect
                            className={styles.panel}
                            x="8"
                            y="108"
                            width="240"
                            height="28"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="16"
                            y="114"
                            width="64"
                            height="16"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="96"
                            y="114"
                            width="64"
                            height="16"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="176"
                            y="114"
                            width="64"
                            height="16"
                            rx="2"
                        />
                    </svg>
                    <h4>Before:</h4>
                    <p>
                        Slow onboarding, inconsistent UI, hard-to-debug layouts.
                    </p>
                    <h4>After:</h4>
                    <p>
                        Design system onboarding documentation and team
                        upskilling.
                    </p>
                </Card>
                <Card title="Ecommerce platform" size="md">
                    <svg
                        className={styles.visual}
                        aria-hidden="true"
                        viewBox="0 0 256 144"
                    >
                        <rect className="bg" width="256" height="144" />
                        <rect
                            className={styles.panel}
                            x="0"
                            y="0"
                            width="256"
                            height="16"
                        />
                        <rect
                            className={styles.block}
                            x="8"
                            y="4"
                            width="36"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="212"
                            y="4"
                            width="36"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.panel}
                            x="8"
                            y="24"
                            width="240"
                            height="40"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="16"
                            y="32"
                            width="80"
                            height="24"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="104"
                            y="32"
                            width="92"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="104"
                            y="46"
                            width="60"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.panel}
                            x="8"
                            y="72"
                            width="116"
                            height="36"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="16"
                            y="78"
                            width="28"
                            height="24"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="48"
                            y="78"
                            width="68"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="48"
                            y="92"
                            width="44"
                            height="8"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="132"
                            y="72"
                            width="116"
                            height="36"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="140"
                            y="78"
                            width="28"
                            height="24"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="172"
                            y="78"
                            width="68"
                            height="8"
                            rx="1"
                        />
                        <rect
                            className={styles.block}
                            x="172"
                            y="92"
                            width="44"
                            height="8"
                            rx="2"
                        />
                        <rect
                            className={styles.panel}
                            x="8"
                            y="114"
                            width="240"
                            height="22"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="16"
                            y="119"
                            width="120"
                            height="12"
                            rx="2"
                        />
                        <rect
                            className={styles.block}
                            x="142"
                            y="119"
                            width="98"
                            height="12"
                            rx="2"
                        />
                    </svg>
                    <h4>Before:</h4>
                    <p>
                        Flaky components, accessibility gaps, shipping delays.
                    </p>
                    <h4>After:</h4>
                    <p>Accessible component library and automated testing.</p>
                </Card>
            </div>
            <div className={styles.cta}>
                <p>Want these results for your team?</p>
                <BookCallButton />
            </div>
        </Section>
    );
}
