import styles from "./CaseStudies.module.scss";

export default function EcommerceVisual() {
    return (
        <svg className={styles.visual} aria-hidden="true" viewBox="0 0 256 144">
            <rect className="bg" width="256" height="144" />
            <rect
                className={styles.panel}
                x="-1"
                y="-1"
                width="258"
                height="17"
            />
            <rect
                className={styles.block}
                x="8"
                y="4"
                width="36"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="212"
                y="4"
                width="36"
                height="8"
                rx="1"
            />
            <rect
                className={styles.panel}
                x="8"
                y="24"
                width="240"
                height="40"
                rx="2"
            />
            <rect
                className={styles.block}
                x="16"
                y="32"
                width="80"
                height="24"
                rx="2"
            />
            <rect
                className={styles.block}
                x="104"
                y="32"
                width="92"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="104"
                y="46"
                width="60"
                height="8"
                rx="1"
            />
            <rect
                className={styles.panel}
                x="8"
                y="72"
                width="116"
                height="36"
                rx="2"
            />
            <rect
                className={styles.block}
                x="16"
                y="78"
                width="28"
                height="24"
                rx="2"
            />
            <rect
                className={styles.block}
                x="48"
                y="78"
                width="68"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="48"
                y="92"
                width="44"
                height="8"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="132"
                y="72"
                width="116"
                height="36"
                rx="2"
            />
            <rect
                className={styles.block}
                x="140"
                y="78"
                width="28"
                height="24"
                rx="2"
            />
            <rect
                className={styles.block}
                x="172"
                y="78"
                width="68"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="172"
                y="92"
                width="44"
                height="8"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="8"
                y="114"
                width="240"
                height="22"
                rx="2"
            />
            <rect
                className={styles.block}
                x="16"
                y="119"
                width="120"
                height="12"
                rx="2"
            />
            <rect
                className={styles.block}
                x="142"
                y="119"
                width="98"
                height="12"
                rx="2"
            />
        </svg>
    );
}
