import styles from "./CaseStudies.module.scss";

export default function GlobalFintechVisual() {
    return (
        <svg className={styles.visual} aria-hidden="true" viewBox="0 0 256 144">
            <rect className="bg" width="256" height="144" />
            <rect
                className={styles.panel}
                x="0"
                y="0"
                width="36"
                height="144"
            />
            <rect
                className={styles.block}
                x="6"
                y="8"
                width="24"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="6"
                y="24"
                width="24"
                height="6"
                rx="1"
            />
            <rect
                className={styles.block}
                x="6"
                y="34"
                width="24"
                height="6"
                rx="1"
            />
            <rect
                className={styles.block}
                x="6"
                y="44"
                width="24"
                height="6"
                rx="1"
            />
            <rect
                className={styles.block}
                x="6"
                y="54"
                width="24"
                height="6"
                rx="1"
            />
            <rect
                className={styles.panel}
                x="36"
                y="0"
                width="220"
                height="20"
            />
            <rect
                className={styles.block}
                x="42"
                y="6"
                width="30"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="76"
                y="6"
                width="30"
                height="8"
                rx="1"
            />
            <rect
                className={styles.block}
                x="110"
                y="6"
                width="30"
                height="8"
                rx="1"
            />
            <rect
                className={styles.panel}
                x="42"
                y="28"
                width="46"
                height="20"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="94"
                y="28"
                width="46"
                height="20"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="146"
                y="28"
                width="46"
                height="20"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="198"
                y="28"
                width="46"
                height="20"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="42"
                y="54"
                width="120"
                height="50"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="168"
                y="54"
                width="76"
                height="50"
                rx="2"
            />
            <rect
                className={styles.panel}
                x="42"
                y="110"
                width="202"
                height="26"
                rx="2"
            />
        </svg>
    );
}
