name: Release
on:
    push:
        branches:
            - master

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
                  cache-dependency-path: |
                      **/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Lint files
              run: npm run lint

            - name: Restore Next.js cache
              uses: actions/cache@v4
              with:
                  path: .next/cache
                  key: ${{ runner.os }}-next-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-next-

            - name: Run build storybook
              run: npm run build-storybook

            - name: Build
              run: npm run build

            - name: Set domain CNAME
              run: echo "lapidist.net" >> out/CNAME

            - name: Touch .nojekyll
              run: touch out/.nojekyll

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  branch: gh-pages
                  folder: out
                  clean: true

            - name: Deploy Storybook
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  repository-name: bylapidist/website-storybook
                  branch: gh-pages
                  folder: storybook-static
                  clean: true
