name: Test
on: [pull_request]

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.61.1-noble
            options: --ipc=host

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 1

            - name: Fix git safe directory
              run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

            - name: Setup pnpm
              uses: pnpm/action-setup@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm

            # Prevent browser download during pnpm install
            - name: Install deps (no browsers)
              run: pnpm install --frozen-lockfile
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

            - name: Knip
              run: pnpm run knip

            - name: Lint
              run: pnpm run lint

            - name: Type check
              run: pnpm run typecheck

            - name: Test
              run: pnpm run test:unit && pnpm run test:e2e
