name: Test
on: [pull_request]

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.56.1-noble
            options: --ipc=host

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 1

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: npm
                  cache-dependency-path: |
                      **/package-lock.json

            # Prevent browser download during npm ci
            - name: Install deps (no browsers)
              run: npm ci
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

            - name: Lint
              run: npm run lint

            - name: Design lint
              run: npm run lint:design

            - name: Type check
              run: npm run typecheck

            - name: Test
              run: npm run test:unit && npm run test:e2e

            - name: Lighthouse
              run: |
                  export CHROME_PATH=$(node -e "process.stdout.write(require('@playwright/test').chromium.executablePath())")
                  npm run qa
              env:
                  NODE_ENV: production

            - name: Build Storybook
              run: npm run build-storybook

            - name: Storybook a11y
              run: npm run test:storybook
